services:
  postgres:
    image: postgres:16
    container_name: workflex_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: workflex_user
      POSTGRES_PASSWORD: workflex_secret
      POSTGRES_DB: workflex_db
    ports:
      - "5433:5432"
    volumes:
      - workflex_pgdata:/var/lib/postgresql/data

volumes:
  workflex_pgdata:
